# Generated by Django 4.1.4 on 2023-09-18 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenWeatherApi', '0002_alter_city_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
